# git_info.cmake — run at BUILD time (not configure time): writes ${OUT} with the short git
# hash of the source tree, suffixed "-dirty" when tracked files differ from HEAD. The file is
# only rewritten when the content changes, so unchanged builds do not recompile.
execute_process(COMMAND git rev-parse --short HEAD WORKING_DIRECTORY ${SRC}
                OUTPUT_VARIABLE H OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
execute_process(COMMAND git status --porcelain --untracked-files=no WORKING_DIRECTORY ${SRC}
                OUTPUT_VARIABLE D OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
if(NOT H)
  set(H "nogit")
endif()
if(D)
  set(H "${H}-dirty")
endif()
set(content "// generated by cmake/git_info.cmake — do not edit\n#pragma once\n#define PS26119_GIT_HASH \"${H}\"\n")
set(old "")
if(EXISTS ${OUT})
  file(READ ${OUT} old)
endif()
if(NOT "${old}" STREQUAL "${content}")
  file(WRITE ${OUT} "${content}")
endif()
