// test_integration.cpp — the unified pipeline after integrating gpuopt: MPS reader → Model →
// solve() with every engine → verification gate. Also the gate itself on fabricated answers.
#include <gtest/gtest.h>

#include <cmath>
#include <string>

#include "core/gate.h"
#include "io/lpm_reader.h"
#include "io/mps_reader.h"
#include "ps26119/solve.h"

using namespace ps26119;

namespace {
const std::string kData = std::string(PS26119_SOURCE_DIR) + "/data/";

Model mps(const std::string& rel) {
  Model m;
  std::string err;
  EXPECT_TRUE(io::read_mps(kData + rel, m, err)) << err;
  return m;
}
}  // namespace

// Two independent readers (teammate's MPS parser, our .lpm bridge generated by highspy)
// must produce the same Model on every committed instance (CLAUDE.md §2).
TEST(Integration, MpsReaderMatchesLpmBridgeOnCommittedData) {
  for (const char* name : {"netlib_small/afiro", "netlib_small/sc50a", "netlib_small/sc50b", "netlib_small/kb2",
                           "netlib_small/adlittle", "netlib_small/blend", "netlib_small/share2b",
                           "netlib_small/sc105", "netlib_small/stocfor1", "netlib_small/recipe", "hand/max_ranged",
                           "hand/knapsack_mip"}) {
    Model a = mps(std::string(name) + ".mps"), b;
    ASSERT_TRUE(io::read_lpm(kData + name + ".lpm", b).ok) << name;
    EXPECT_EQ(a.fingerprint_hex(), b.fingerprint_hex()) << name;
  }
}

TEST(Integration, ReadMpsReportsErrorsWithoutThrowing) {
  Model m;
  std::string err;
  EXPECT_FALSE(io::read_mps(kData + "does/not/exist.mps", m, err));
  EXPECT_FALSE(err.empty());
  std::vector<std::string> warnings;
  ASSERT_TRUE(io::read_mps(kData + "examples/features.mps", m, err, &warnings)) << err;
  EXPECT_EQ(warnings.size(), 1u);  // negative UP with default lower bound
}

// Every LP engine, same Model, same Solution contract, same answer, all gated PASS.
TEST(Integration, AllEnginesAgreeAndPassTheGate) {
  for (const char* name : {"netlib_small/afiro", "netlib_small/adlittle", "netlib_small/blend", "hand/max_ranged"}) {
    const Model m = mps(std::string(name) + ".mps");
    double ref = std::nan("");
    for (Algorithm a : {Algorithm::Oracle, Algorithm::Simplex, Algorithm::R2hpdhg, Algorithm::Pdlp}) {
      for (bool presolve : {false, true}) {
        Options o;
        o.algorithm = a;
        o.presolve = presolve;
        const Solution s = solve(m, o);
        ASSERT_EQ(s.status, Status::Optimal) << name << " " << to_string(a) << " presolve=" << presolve << ": " << s.message;
        EXPECT_EQ(s.check, "PASS") << name << " " << to_string(a);
        EXPECT_EQ(s.model_fingerprint, m.fingerprint_hex());
        if (std::isnan(ref)) ref = s.objective;
        EXPECT_NEAR(s.objective, ref, 1e-6 * (1 + std::fabs(ref))) << name << " " << to_string(a);
      }
    }
  }
}

TEST(Integration, SimplexEngineIdentityAndKnobs) {
  const Model m = mps("netlib_small/afiro.mps");
  Options o;
  o.algorithm = Algorithm::Simplex;
  o.presolve = false;
  Solution s = solve(m, o);
  ASSERT_EQ(s.status, Status::Optimal);
  EXPECT_EQ(s.engine, "simplex");
  EXPECT_TRUE(std::isfinite(s.certified_bound));  // afiro: finite, tight certified bound
  EXPECT_LE(s.certified_bound, s.objective + 1e-9);
  o.engine_params = {{"simplex_pricing", 0}, {"simplex_scale", 0}, {"simplex_perturb", 0}};
  EXPECT_EQ(solve(m, o).status, Status::Optimal);
  o.engine_params = {{"reflection", 1}};  // a PDHG knob is unknown to the simplex
  s = solve(m, o);
  EXPECT_EQ(s.status, Status::NotSolved);
  EXPECT_NE(s.message.find("unknown simplex engine parameter"), std::string::npos);
  Algorithm parsed;
  ASSERT_TRUE(algorithm_from_string("simplex", parsed));
  EXPECT_EQ(parsed, Algorithm::Simplex);
}

TEST(Integration, InfeasibleAndUnboundedExamples) {
  for (Algorithm a : {Algorithm::Simplex, Algorithm::Oracle}) {
    Options o;
    o.algorithm = a;
    EXPECT_EQ(solve(mps("examples/infeasible.mps"), o).status, Status::Infeasible) << to_string(a);
    EXPECT_EQ(solve(mps("examples/unbounded.mps"), o).status, Status::Unbounded) << to_string(a);
  }
}

// ---- the gate on fabricated answers

TEST(Gate, DemotesAWrongOptimalFromAnExactEngine) {
  const Model m = mps("netlib_small/afiro.mps");
  Options o;
  o.algorithm = Algorithm::Simplex;
  Solution s = solve(m, o);
  ASSERT_EQ(s.check, "PASS");
  Solution bad = s;
  bad.x[0] += 1.0;  // breaks a row
  core::gate(m, o, bad);
  EXPECT_EQ(bad.status, Status::NumericalError);
  EXPECT_EQ(bad.check, "FAIL");
  EXPECT_NE(bad.message.find("Optimal withdrawn"), std::string::npos);
  Solution nodual = s;
  nodual.y.clear();
  core::gate(m, o, nodual);
  EXPECT_EQ(nodual.status, Status::NumericalError);
}

TEST(Gate, FirstOrderKeepsItsLooserToleranceButRecordsTheFailure) {
  const Model m = mps("netlib_small/afiro.mps");
  Options o;  // r2hpdhg
  o.tolerance = 1e-8;
  Solution s = solve(m, o);
  ASSERT_EQ(s.status, Status::Optimal);
  ASSERT_EQ(s.check, "PASS");
  Solution bad = s;
  bad.x[0] += 1.0;
  core::gate(m, o, bad);  // 1e-8 promises verifier-grade accuracy
  EXPECT_EQ(bad.status, Status::NumericalError);
  bad = s;
  bad.x[0] += 1.0;
  o.tolerance = 1e-4;  // "fast" mode does not
  core::gate(m, o, bad);
  EXPECT_EQ(bad.status, Status::Optimal);
  EXPECT_EQ(bad.check, "FAIL");
}

TEST(Gate, LeavesNonOptimalAndMilpAlone) {
  const Model lp = mps("netlib_small/afiro.mps");
  Solution s;
  s.status = Status::TimeLimit;
  core::gate(lp, Options{}, s);
  EXPECT_EQ(s.status, Status::TimeLimit);
  EXPECT_TRUE(s.check.empty());
  const Model mip = mps("hand/knapsack_mip.mps");
  const Solution ms = solve(mip);
  EXPECT_EQ(ms.status, Status::Optimal);
  EXPECT_TRUE(ms.check.empty());
}
